# Generated by ORMatic

from __future__ import annotations
from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    String,
    Float,
    Boolean,
    DateTime,
    Enum,
    JSON,
    Table,
)
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase

import builtins
import coraplex.datastructures.enums
import coraplex.orm.model
import enum
import krrood.adapters.json_serializer
import krrood.ormatic.custom_types
import krrood.ormatic.data_access_objects.alternative_mappings
import krrood.ormatic.type_dict
import numpy
import pathlib
import semantic_digital_twin.orm.model
import semantic_digital_twin.world_description.degree_of_freedom
import semantic_digital_twin.world_description.world_entity
import sqlalchemy.sql.sqltypes
import typing
import typing_extensions
import uuid


from krrood.ormatic.data_access_objects.dao import (
    DataAccessObject,
    AssociationDataAccessObject,
)
from krrood.ormatic.custom_types import TypeType


class Base(DeclarativeBase):
    type_mappings = {
        numpy.ndarray: coraplex.orm.model.NumpyType,
        typing.Type: krrood.ormatic.custom_types.TypeType,
        builtins.type: krrood.ormatic.custom_types.TypeType,
        enum.Enum: krrood.ormatic.custom_types.PolymorphicEnumType,
        krrood.adapters.json_serializer.SubclassJSONSerializer: sqlalchemy.sql.sqltypes.JSON,
        uuid.UUID: sqlalchemy.sql.sqltypes.UUID,
        pathlib.Path: krrood.ormatic.custom_types.PathType,
        krrood.adapters.json_serializer.JSONData: krrood.ormatic.custom_types.JSONDataType,
    }


# Association tables for many-to-many relationships


class PlanMappingDAO(Base, DataAccessObject[coraplex.orm.model.PlanMapping]):
    __tablename__ = "PlanMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    initial_world_id: Mapped[typing.Optional[builtins.int]] = mapped_column(
        ForeignKey("WorldMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    initial_world: Mapped[WorldMappingDAO] = relationship(
        "WorldMappingDAO",
        uselist=False,
        foreign_keys=[initial_world_id],
        post_update=True,
    )


class FunctionMappingDAO(
    Base,
    DataAccessObject[
        krrood.ormatic.data_access_objects.alternative_mappings.FunctionMapping
    ],
):
    __tablename__ = "FunctionMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    module_name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    function_name: Mapped[builtins.str] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )
    class_name: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )


class HomogeneousTransformationMatrixMappingDAO(
    Base,
    DataAccessObject[
        semantic_digital_twin.orm.model.HomogeneousTransformationMatrixMapping
    ],
):
    __tablename__ = "HomogeneousTransformationMatrixMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    child_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    position_id: Mapped[int] = mapped_column(
        ForeignKey("Point3MappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    rotation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    position: Mapped[Point3MappingDAO] = relationship(
        "Point3MappingDAO", uselist=False, foreign_keys=[position_id], post_update=True
    )
    rotation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[rotation_id],
        post_update=True,
    )


class Point3MappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Point3Mapping]
):
    __tablename__ = "Point3MappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class PoseMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.PoseMapping]
):
    __tablename__ = "PoseMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )
    polymorphic_type: Mapped[str] = mapped_column(
        String(255), nullable=False, use_existing_column=True
    )

    position_id: Mapped[int] = mapped_column(
        ForeignKey("Point3MappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )
    orientation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    position: Mapped[Point3MappingDAO] = relationship(
        "Point3MappingDAO", uselist=False, foreign_keys=[position_id], post_update=True
    )
    orientation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[orientation_id],
        post_update=True,
    )

    __mapper_args__ = {
        "polymorphic_on": "polymorphic_type",
        "polymorphic_identity": "PoseMappingDAO",
    }


class GrasPoseMappingDAO(
    PoseMappingDAO, DataAccessObject[coraplex.orm.model.GrasPoseMapping]
):
    __tablename__ = "GrasPoseMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        ForeignKey(PoseMappingDAO.database_id),
        primary_key=True,
        use_existing_column=True,
    )

    arm: Mapped[typing.Optional[coraplex.datastructures.enums.Arms]] = mapped_column(
        krrood.ormatic.custom_types.PolymorphicEnumType,
        nullable=True,
        use_existing_column=True,
    )

    __mapper_args__ = {
        "polymorphic_identity": "GrasPoseMappingDAO",
        "inherit_condition": database_id == PoseMappingDAO.database_id,
        "polymorphic_load": "selectin",
    }


class Pose2DMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Pose2DMapping]
):
    __tablename__ = "Pose2DMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    yaw: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class QuaternionMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.QuaternionMapping]
):
    __tablename__ = "QuaternionMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    w: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class RotationMatrixMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.RotationMatrixMapping]
):
    __tablename__ = "RotationMatrixMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )

    rotation_id: Mapped[int] = mapped_column(
        ForeignKey("QuaternionMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    rotation: Mapped[QuaternionMappingDAO] = relationship(
        "QuaternionMappingDAO",
        uselist=False,
        foreign_keys=[rotation_id],
        post_update=True,
    )


class Vector3MappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.Vector3Mapping]
):
    __tablename__ = "Vector3MappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    x: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    y: Mapped[builtins.float] = mapped_column(use_existing_column=True)
    z: Mapped[builtins.float] = mapped_column(use_existing_column=True)

    reference_frame: Mapped[
        typing.Optional[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(
        sqlalchemy.sql.sqltypes.JSON, nullable=True, use_existing_column=True
    )


class WorldMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.WorldMapping]
):
    __tablename__ = "WorldMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    name: Mapped[typing.Optional[builtins.str]] = mapped_column(
        sqlalchemy.sql.sqltypes.Text, use_existing_column=True
    )

    kinematic_structure_entities: Mapped[
        typing.List[
            semantic_digital_twin.world_description.world_entity.KinematicStructureEntity
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    connections: Mapped[
        typing.List[semantic_digital_twin.world_description.world_entity.Connection]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    semantic_annotations: Mapped[
        typing.List[
            semantic_digital_twin.world_description.world_entity.SemanticAnnotation
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)
    degrees_of_freedom: Mapped[
        typing.List[
            semantic_digital_twin.world_description.degree_of_freedom.DegreeOfFreedom
        ]
    ] = mapped_column(JSON, nullable=False, use_existing_column=True)

    state_id: Mapped[int] = mapped_column(
        ForeignKey("WorldStateMappingDAO.database_id", use_alter=True),
        nullable=True,
        use_existing_column=True,
    )

    state: Mapped[WorldStateMappingDAO] = relationship(
        "WorldStateMappingDAO", uselist=False, foreign_keys=[state_id], post_update=True
    )


class WorldStateMappingDAO(
    Base, DataAccessObject[semantic_digital_twin.orm.model.WorldStateMapping]
):
    __tablename__ = "WorldStateMappingDAO"

    database_id: Mapped[builtins.int] = mapped_column(
        Integer, primary_key=True, use_existing_column=True
    )

    data: Mapped[typing.List[builtins.float]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )
    ids: Mapped[typing.List[uuid.UUID]] = mapped_column(
        JSON, nullable=False, use_existing_column=True
    )
